nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization', 'origin', 'accept', 'bearer']
    expose_headers: ['Link']
    max_age: 3600
    allow_credentials: true
    forced_allow_origin_value: 'http://127.0.0.1:8080'
  paths:
    '^/': ~