version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - '8081:80'
